import sys

from nestargs import NestedArgumentParser

from lib.formatter import RawFormatter

eval_parser = NestedArgumentParser(
    description='RESTORE-DiT (Evaluation)',
    formatter_class=RawFormatter
)

eval_parser.add_argument('config_file', metavar='config-file', type=str, help='Configuration file generated by run_train.py (runtime config during training)')
eval_parser.add_argument(
    'method', type=str, choices=['trivial', 'SDT',])

eval_parser.add_argument(
    '--checkpoint', type=str, help='Model checkpoint'
)
eval_parser.add_argument(
    '--mode', type=str, required='trivial' in sys.argv, help='Mode for non-learned baselines',
    choices=['last', 'next', 'closest', 'linear_interpolation']
)

# Optional arguments to overwrite the data settings in the config file
eval_parser.add_argument('--test-data.test-config', type=str, required=False, help='YAML configuration file, test-specific settings')
eval_parser.add_argument('--test-data.data-dir', type=str, required=False, help='Root directory of the dataset')
eval_parser.add_argument(
    '--test-data.hdf5-file', type=str, required=False, help='HDF5 test dataset, path relative to <data-dir>')
eval_parser.add_argument('--test-data.split', type=str, required=False, help='Data split')
eval_parser.add_argument('--test-data.mode', type=str, required=False, help='Data mode (for EarthNet2021 only)')

eval_parser.add_argument('--test-data.rescale', type=bool, default=False, help='rescale to [-1,1], for diffusion models only')
eval_parser.add_argument('--inference_steps', type=int, default=1, help='(nums of inference steps, for diffusion models only')

